### ISSUE TITLE
開発環境を構築する

### ISSUE THREAD

**Issue by IN00** [IN00/self_introduction#1]

**Comment by IN00** [comment]
# 参考

[【新規・途中採用】RailsのDBにMySQLを使う手順 \| shin>>media](https://shinmedia20.com/rails-db-mysql)

**Comment by IN00** [comment]
# bundle exec db:create エラー問題


エラー内容
```
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Couldn't create 'self_introduction_development' database. Please check your configuration.
rails aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:912:in `try_to_checkout_new_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:873:in `acquire_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:595:in `checkout'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:439:in `connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1121:in `retrieve_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:238:in `retrieve_connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:206:in `connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/mysql_database_tasks.rb:8:in `connection'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/mysql_database_tasks.rb:16:in `create'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:126:in `create'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:476:in `each'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:475:in `each'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <main>'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

mysqlサーバーを起動しながらでないとダメっぽい

```
--- dev/self_introduction ‹master* ?› » mysql.server start                                                                                                                                 1 ↵
Starting MySQL
. SUCCESS!
--- dev/self_introduction ‹master* ?› » bundle exec rails db:create
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/ivankov/dev/self_introduction/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Created database 'self_introduction_development'
Created database 'self_introduction_test'
```

参考
[railsのapp作成でmysqlを使用する時の導入とハマるところ　rake db:createができるまでの流れ　　　 \- Qiita](https://qiita.com/Kaisyou/items/17142ff2d080d565fedc)
